name: stylo2
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - python=3.10
  - ipython
  - pip
  - pip:
      - torch==2.2.1
      - torchmetrics==1.7.3
      - torchvision==0.17.1
      - pytorch-lightning==1.5.0
      - einops
      - opencv-python==4.7.0.72
      - matplotlib
      - omegaconf
      - albumentations
      - transformers==4.44.2
      - xformers==0.0.25
      - triton
      - open-clip-torch==2.19.0
      - diffusers==0.20.2
      - scipy
      - scikit-image==0.25.2
      - clean-fid==0.1.35
      - numpy==1.26.4
      - fire
      - pillow
      - sentencepiece
      - protobuf
      - webdataset
      - accelerate==0.28.0
      - pyarrow==15.0.2
      - ftfy==6.2.0
      - tensorboard==2.14.0
      - datasets==2.18.0
      - jupyterlab==4.1.6
      - transparent-background==1.2.12

